### ISSUE TITLE
Prepare the app for publication

### ISSUE THREAD

**Issue by rudolfs** [getsenic/senic-home-automation-app#33]
# Apple App Store

- [x] Ask copy team to prepare metadata https://developer.apple.com/app-store/product-page/ (https://docs.google.com/document/d/1l8Oso4Qqg0EOZgqOJZqJYOkEIxYRjX4VcZav_Xg5uw0)
  - [x] App name ("Senic")
  - [x] Subtitle
  - [x] Icon
  - [x] App preview video (do we have time to do this? -> Use the tutorial video)
  - [x] Screenshots -> set up fastlane (ask design team which screens)
  - [x] Description
  - [ ] Promo text
  - [x] Keywords
  - [x] What's new (changelog)
  - [x] Category and 2nd category https://developer.apple.com/app-store/categories/
  - [x] Price (free?)
  - [x] App (age) rating
  - [x] Release date
  - [x] Release countries -> all of them
- [ ] App id / certificate / provisioning profile -> set up fastlane
- [x] Make sure the app works on ipad and other screen resolutions -> fastlane can generate screenshots for all display sizes
- [x] Decide what should be the minimal required hw and ios version that our app will run on
- [x] Add Terms of Service screen (#30)
- [x] Prepare demo video (screen recording) of on-boarding + app usage for the reviewers
- [x] The "contact us" page should show a spinner while it's loading, and do proper error handling in case the website unreachable (#37)
- [ ] Implement UI design suggestions (#47, #48)
- [x] Fix copy (#50)
- [x] More -> Support is a TODO, implement or remove (#38)
- [x] More -> Hub Settings is a TODO, implement or remove (#38)
- [x] More -> We need only one reset button "Reset app" or "Reset app & Hub" figure out which one to keep maybe have one only in the dev build (#38)

### Apple provided checklist:
- [x] Test your app for crashes and bugs
- [x] Ensure that all app information and metadata is complete and accurate
- [x] Update your contact information in case App Review needs to reach you
- [x] Provide an active demo account and login information, plus any other hardware or resources that might be needed to review your app (e.g. login credentials or a sample QR code)
- [x] Enable backend services so that they’re live and accessible during review
- [x] Include detailed explanations of non-obvious features and in-app purchases in the App Review notes, including supporting documentation where appropriate. If we’re not able to access part of your app because it’s geo-locked or otherwise restricted, provide a link to a video of the functionality

### Relevant paragraphs from App Store Review Guidelines
https://developer.apple.com/app-store/review/guidelines/

2.3.1 Don’t include any hidden or undocumented features in your app; your app’s functionality should be clear to end-users and App Review.

2.3.3 Screenshots should show the app in use, and not merely the title art, log-in page, or splash screen. They may also include text and image overlays (e.g. to demonstrate input mechanisms, such as an animated touch point or Apple Pencil) and show extended functionality on device, such as Touch Bar.

2.3.7 Choose a unique app name, assign keywords that accurately describe your app, and don’t try to pack any of your metadata with trademarked terms, popular app names, or other irrelevant phrases just to game the system. App names must be limited to 30 characters and should not include prices, terms, or descriptions that are not the name of the app. App subtitles are a great way to provide additional context for your app; they must follow our standard metadata rules and should not include inappropriate content, reference other apps, or make unverifiable product claims. Apple may modify inappropriate keywords at any time.

2.4.1 To ensure people get the most out of your app, iPhone apps should run on iPad whenever possible. We encourage you to consider building universal apps so customers can use them on all of their devices. Learn more about Universal apps.

2.5.5 We will be reviewing on an IPv6 network, so if your app isn’t compatible with the IPv6 addressing, it may fail during review.

(i) Apps that collect user or usage data must have a privacy policy and secure user consent for the collection. This includes—but isn’t limited to—apps that implement HealthKit or other health/medical technologies, apps that utilize ARKit, Camera APIs, Photo APIs, or other software for depth of facial mapping information, HomeKit, Keyboard extensions, Apple Pay, Stickers and iMessage extensions, include a login, or access user data from the device. Your app description should let people know what types of access (e.g. location, contacts, calendar, etc.) are requested by your app, and what aspects of the app won’t work if the user doesn’t grant permission.

# Google Play Store

- [x] Title (same as app name <= 50 characters)
- [x] Short Description ( <= 80 characters)
- [x] Full Description ( <= 4000 characters)
- [x] Application type and category
- [x] Contact details
- [x] Content ratings
- [x] Privacy policy
- [x] Publish date
- [x] Price
- [x] Which countries should the app be released to
- [x] Icon
- [x] Feature Graphic
- [ ] Video trailer (do we need one?)
- [x] Screenshots
- [ ] Remove unneeded permissions (coarse location, contacts. probably can't https://github.com/Polidea/react-native-ble-plx/issues/109)

https://developer.android.com/distribute/best-practices/launch/launch-checklist.html
https://developer.android.com/studio/publish/preparing.html
https://developer.android.com/distribute/best-practices/launch/beta-tests.html
https://support.google.com/googleplay/android-developer/answer/7353455?visit_id=1-636524839553023083-3965703965&rd=1
https://developer.android.com/distribute/best-practices/launch/pre-launch-crash-reports.html
https://support.google.com/googleplay/android-developer/answer/7002270

# Documentation for the rest of the team

https://docs.google.com/document/d/1RcLiCo6w3AtqqkfXhAtKjVrQVlJtsZ5Y8arr9-MmYFQ/edit#heading=h.plfv9k7z2k1o

**Comment by rudolfs** [comment]
App Store metadata:
https://docs.google.com/document/d/1l8Oso4Qqg0EOZgqOJZqJYOkEIxYRjX4VcZav_Xg5uw0/

Screenshots:
https://drive.google.com/drive/u/0/folders/0BySJjvi3Td9tcGNGejdaQ1ZzYUU

Submission Review additional notes for App Store:
https://docs.google.com/document/d/13wokKG-Nlfx8VvuvDkLb-us1WYqj_s6EiS3B8Xq3AVM
